name: Build and test
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install ansible
      - name: Install PSUTIL
        run: pip install psutil netifaces
      - name: Building the collection
        run: ansible-galaxy collection build .
      - name: Installing the collection
        run: ansible-galaxy collection install some-some*
#      - name: Running sanity test
#        run: pushd ~/.ansible/collections/ansible_collections/some/some && ansible-test sanity && popd
  publish-local:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'ref/heads/main'
    steps:
     - uses: actions/upload-artifact@v4
       with:
         name: some-some-${{ github.sha }}
         retention-days: 7
         path: some-some*