name: Build and test
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install ansible
#      - name: Install PSUTIL
#        run: pip install psutil netifaces
      - name: Download cert
        run: mkdir roles/asd/files && wget https://ca.dynatrace.com/dt-root.cert.pem -P roles/asd/files
      - name: Building the collection
        run: ansible-galaxy collection build .
      - name: dddddddddd
        run: echo ${{ github.ref }}
      - name: Upload artifact
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          name: some-some-${{ github.sha }}
          retention-days: 7
          path: some-some*

