name: Publish
on:
  push:
    tags:
      - v*

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run echo
        run: echo Publishing
      - name: GITHUB SHA
        run: echo ${{ github.sha }}
#      - name: Download artifact
#        uses: actions/download-artifact@v4
        with:
          name: some-some-${{ github.sha }}
      - name: RUNRUN
        run: ls -al
